### ISSUE TITLE
Invalid regular expression

### ISSUE THREAD

**Issue by ThallyssonKlein** [rjmunhoz/carbon-telegram-bot#8]
This error is occurring when running the current version:

```
$ node dist/index.js
/home/thallyssonklein/Downloads/carbon-telegram-bot/dist/presentation/handlers/gist.js:15
const regex = /https?:\/\/gist\.github\.com\/(?<username>.+)\/(?<gistId>[a-zA-Z0-9]+)/;
              ^

SyntaxError: Invalid regular expression: /https?:\/\/gist\.github\.com\/(?<username>.+)\/(?<gistId>[a-zA-Z0-9]+)/: Invalid group
    at Object.<anonymous> (/home/thallyssonklein/Downloads/carbon-telegram-bot/dist/presentation/handlers/gist.js:15:15)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/thallyssonklein/Downloads/carbon-telegram-bot/dist/presentation/handlers/index.js:6:32)
    at Module._compile (module.js:652:30)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by ThallyssonKlein** [comment]
I resolved by updating the node version and installing the nodemon

**Comment by rjmunhoz** [comment]
@ThallyssonKlein thanks! I'll take a look at it and update the repo
